spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:43306/ddip?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
